server:
  port: 8084

spring:
  application:
    name: CLOUD-CONSUMER-HYSTRIX-ORDER

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka
feign:
  hystrix:
    enabled: true
